name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_network
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Angelo
      - APELLIDO=Gomez
      - DOCUMENTO=12345678
      - NACIMIENTO=1990-01-01
      - NUMERO=5555 
    networks:
      - testing_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

networks:
  testing_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
