name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_network
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Angelo
      - APELLIDO=Gomez
      - DOCUMENTO=12345678
      - NACIMIENTO=1990-01-01
      - NUMERO=5555 
    networks:
      - testing_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Fyssi
      - APELLIDO=Perez
      - DOCUMENTO=87654321
      - NACIMIENTO=1985-05-15
      - NUMERO=1032 
    networks:
      - testing_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Rebeca
      - APELLIDO=Garcia
      - DOCUMENTO=11223344
      - NACIMIENTO=1992-09-30
      - NUMERO=1554 
    networks:
      - testing_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Abraham
      - APELLIDO=Rodriguez
      - DOCUMENTO=44332211
      - NACIMIENTO=1988-12-20
      - NUMERO=7090 
    networks:
      - testing_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Adrian
      - APELLIDO=Lopez
      - DOCUMENTO=56789012
      - NACIMIENTO=1995-07-10
      - NUMERO=2518 
    networks:
      - testing_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

networks:
  testing_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
